### ISSUE TITLE
1.2.1 Release Checklist

### ISSUE THREAD

**Issue by glennblock** [splunk/splunk-sdk-java#55]
These are instructions on the various steps necessary to put out a new release of the Splunk SDK for Java. Even though the instructions are public, these steps are only meant to be taken by the SDK maintainers.
## Prerequisites
- [x] Update changelog.
- [x] Run test suite on full test matrix.
- [x] Install `random_numbers.spl` (found in `dist/` after running `ant dist` on the repository) on Linux (32-bit and 64-bit), MacOS X (64-bit), and Windows (32-bit and 64-bit), for all supported versions of Splunk in the test matrix, create a new random_numbers input, and check that it generates events by running the search "*" with time range "Real time (all time)".
- [x] Run all examples.
- [x] Run all dev.splunk.com code samples.
- [x] Remove old temporary branches. This includes feature branches, old release branches, and most branches that have been merged to develop.
  - (Exception: The "promises-old" branch in the JavaScript SDK should be retained for the time being.)
### Release Steps
- [x] Create release branch off of develop (`release/1.2.1`).
  - `git checkout develop`
  - `git pull`
  - `git checkout -b release/1.2.1`
- [x] Update the version number:
  - Update the `version.number` property in the `build.xml`
    file in the root directory.
  - Update the `User-Agent` field of the `HttpService` class.
  - Update README.md
  - Update the line `declare -r version="??"` in `deploy`.
  - Update the version everywhere in `deploy.md`.
- [x] Make sure the version number change didn't break anything:
  - Install the SDK in a clean VM.
  - Run test suite.
  - Run the SDK examples.
- [x] Build a new JAR and ZIP of the SDK: 
  - Make sure the JAR is built with **JDK 6**.
  - Make sure the files reflect the current version (for example, `splunk-splunk-sdk-java-1.2.1.zip`, `splunk-1.2.1.jar`).
  - Commit the change to the `release/1.2.1` branch.
  - Send the JAR and ZIP files to your Docs team.
- [x] Merge to `master` locally. Ensure the commit message is "Release 1.2.1".
  - `git checkout master`
  - `git merge --no-ff -m "Release 1.2.1" release/1.2.1`
  - `git commit`
- [x] Tag the above commit as `1.2`.
  - `git tag 1.2.1`
- [x] Push the `master` and the `1.2.1` tag to GitHub.
  - `git push origin master`
  - `git push --tags`
- [x] Delete the release branch:
  - `git push origin :release/1.2.1`
  - `git branch -d release/1.2.1`
- [x] Sanity check that released version works:
  - _Check with the Product Manager for what should be done here. (And update this bullet with the decision!)_
- [x] Deploy to ArtifactoryOnline
  - Install [Apache Maven 3](http://maven.apache.org/download.cgi).
    - On Linux download [apache-maven-3.1.0-bin.tar.gz](http://www.poolsaboveground.com/apache/maven/maven-3/3.1.0/binaries/apache-maven-3.1.0-bin.tar.gz), untar to /opt, and add /opt/apache-maven-3.1.0/bin to your path.
    - On OS X with [MacPorts](http://www.macports.org/install.php) installed  
      `sudo port install maven3`
    - On Windows download [apache-maven-3.1.0-bin.zip](http://www.poolsaboveground.com/apache/maven/maven-3/3.1.0/source/apache-maven-3.1.0-src.zip), unzip to %PROGRAMFILES%, and add %PROGRAMFILES%\apache-maven-3.1.0\bin to your path.
  - Create or update ~/.m2/settings.xml with these settings.
    
    ```
    <!-- [Settings Reference]: http://maven.apache.org/settings.html -->
    <settings>
      <activeProfiles>
        <activeProfile>splunk</activeProfile>
      </activeProfiles>
      <profiles>
        <profile>
          <id>splunk</id>
          <repositories>
            <!-- [Splunk artifactory]: http://splunk.artifactoryonline.com -->
            <repository>
              <name>Splunk releases</name>
              <id>splunk-releases</id>
              <url>http://splunk.artifactoryonline.com/splunk/libs-releases/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
            <repository>
              <name>Splunk snapshots</name>
              <id>splunk-snapshots</id>
              <url>http://splunk.artifactoryonline.com/splunk/libs-snapshots/</url>
              <releases>
                <enabled>false</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </repository>
          </repositories>
        </profile>
      </profiles>
      <servers>
        <server>
          <id>splunk-production-artifactory</id>
          <filePermissions>664</filePermissions>
          <directoryPermissions>775</directoryPermissions>
          <username>deployer</username>
          <password>{IJnVXKkQLnQHBIg7IxYqXU8s/TNCnjw+ChQKVxAFPd0=}</password>
        </server>
        <server>
          <id>splunk-staging-artifactory</id>
          <filePermissions>664</filePermissions>
          <directoryPermissions>775</directoryPermissions>
          <username>deployer</username>
          <password>{4QWPly1kZPoHVqDWbIpDV0rgivMCQJ4LXH3ZLAMSrp8=}</password>
        </server>
      </servers>
    </settings>
    ```
  - `./deploy production`
  - Verify the contents of http://splunk.artifactoryonline.com/splunk/libs-releases/com/splunk/splunk/. See [deploy.md](https://github.com/splunk/splunk-sdk-java/blob/dnoble--Deploy-to-Artifactory-Online/deploy.md) for guidance.
- [x] Work with Docs team to:
  - Post ZIP and JAR files.
  - Update Readme. For point releases, the version number needs to be updated at a minimum.
  - Update Changelog, includes a list of changes for the current version.
  - Update Dev Portal and push. For point releases, the "What's new" page and download links need to be updated at the very least.
  - Publish the API Reference (docs.splunk.com/Documentation/SDK).
  - Create both MD5 and SHA-512 hashes from _final_ ZIP download. Docs will contact the Web team to upload these files.
- [x] Verify the posted JAR:
  - Download the JAR and make sure the checksum matches the original file.
- [x] Hand off to marketing to announce. See next section.
### Announce!

Hurrah, the new release is basically done! You can now announce it on the
following channels:
- Twitter (@splunkdev, maybe @splunk)
- Google Groups (splunkdev)
- Dev Portal (http://dev.splunk.com)
- Dev Blog (http://blogs.splunk.com/dev)
